server:
  port: 8000
zuul:
  ignoredServices: '*'
  prefix: /api
  routes:
    produits:
      path: /produits/**
      serviceId: produits
      strip-prefix: true
    commandes:
      path: /commandes/**
      serviceId: commandes
      strip-prefix: false
    authService:
      path: /auth/**
      serviceId: authService
      strip-prefix: false 
      sensitive-headers: Cookie,Set-Cookie  
endpoints:
  routes:
    sensitive: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

