version: "3"

services:
  gateway:
    image: tutorial/gateway
    ports:
      - "8000:8000"
    links:
      - serviceregistry
      - commandes
      - produits
      - authentication
  authentication:
    image: tutorial/authentication
    links:
      - serviceregistry
  serviceregistry:
    image: tutorial/serviceregistry
    ports:
      - "8761:8761"
  produits:
    image: tutorial/produits  
    links:
      - serviceregistry
  commandes:
    image: tutorial/commandes
    links:
      - serviceregistry
      - produits